# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minFunc <- function(x, daten, dataNA) {
    .Call('spass_minFunc', PACKAGE = 'spass', x, daten, dataNA)
}

minFuncMult <- function(x, daten, dataNA, n) {
    .Call('spass_minFuncMult', PACKAGE = 'spass', x, daten, dataNA, n)
}

minFuncBlinded <- function(x, daten, dataNA, n, delta) {
    .Call('spass_minFuncBlinded', PACKAGE = 'spass', x, daten, dataNA, n, delta)
}

